### ISSUE TITLE
AWS: Transit gateway for all VPCs

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#115]
In our AWS clusters, we have a VPC, a public subnet and a NAT gateway with an elastic IP in each Stackable/T2 cluster. As the number of EIPs (elastic IPs) is limited to 5, this might be a limiting factor in the future. 

In this article, AWS describes a solution that might be worth having a look at: https://aws.amazon.com/blogs/networking-and-content-delivery/creating-a-single-internet-exit-point-from-multiple-vpcs-using-aws-transit-gateway/

**Comment by backstreetkiwi** [comment]
Looks like this is no longer an issue, right, @lfrancke , @Jimvin ?

**Comment by lfrancke** [comment]
Agreed
