### ISSUE TITLE
Pluscloud Open: Debian10 template

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#142]

**Comment by lfrancke** [comment]
@backstreetkiwi How important do you think this is after we move to K8s native?

**Comment by backstreetkiwi** [comment]
> @backstreetkiwi How important do you think this is after we move to K8s native?

I have no experience of how the underlying OS/Linux distro affects K8s, sorry. Neither do I know if our own software will work differently then. 
My guess though is that it is not really important. We have Debian10 at least in IONOS and Hetzner. So if we don't see a difference there, we most probably wouldn't need a Debian10 in Pluscloud Open.
So we might close this issue. In the unlikely case that we later on feel the need to have a Debian10  in Pluscloud Open, opening a new issue should be easy. The description was empty after all ;-)

**Comment by backstreetkiwi** [comment]
T2 is discontinued
