### ISSUE TITLE
improve Wireguard reliability

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#147]
During the development of #135, we encountered some issues with Wireguard that we want to tackle.

- [ ] SSH into nodes in Pluscloud Open based Clusters

**Details:** The Wireguard VPN could be set up and connected to. The access via `kubectl` or `k9s` using the config from `resources/kubeconfig` worked fine. The problem is that the SSH access only works to the nodes that have been contacted by other means (like `kubectl` or via HTTP, ...) recently (last 15 or so minutes). 
We investigated this with `tcpdump`, `ssh -vvvv`, and the logs of `sshd` and saw that at least some packets reached the targeted node, but the communication broke soon and the client waited for the key-exchange (at least in my memory). If we cancel SSH, contact the server otherwise (e.g. `kubectl` to the orchestrator) and then retry it, it works fine.
So there seems to be no general problems with routing, security groups or the like. 
**(!)** It could even be a problem with the client, we only tested it with `1.0.20200513-1~20.04.2` on Ubuntu 20.4
We closed #135 anyway, as Wireguard can be used to access all clusters like this:
* set up cluster
* `kubectl get nodes` or so using the provided `kubeconfig`
* SSH into the orchestrator (where the API runs) (e.g. `ssh -i cluster_key centos@orchestrator.stackable.demo`)
* From this server, you can hop into all the others using SSH (e.g. `ssh worker-12`, `ssh-main-1`)

- [ ] DNS replacement on client

*(This could also be a client issue, but should be further investigated.)*
**Details:** We set up the Wireguard client to provide a DNS server so we can reach the cluster nodes by name. On my client (Ubuntu 20.4, `1.0.20200513-1~20.04.2`) this leads to a change in `/etc/resolv.conf` in a way that the DNS server of the cluster (`10.11.12.1` = bastion host) is the new primary name server. This slows down the name resolving on my machine and leads to high latency while browsing the web. Maybe there is no way to prevent this (my knowledge is limited, sorry), but we should further investigate it.

- [ ] IPTABLES
**Details:** We use `iptables` to set up the required routing etc. for the communication via wireguard. During the research in #135, some questions/ideas arose:
- [ ] Are all rules really necessary? In one spike, the one NAT rule was sufficient -> investigate
- [ ] Should we integrate the iptables setup in the wireguard server conf as `PostUp`, `PreDown` attributes? If these rules are only necessary for wireguard use, we should do this!

**Comment by lfrancke** [comment]
@backstreetkiwi This is relatively old. Is it still relevant and you'd still say it is medium priority?

**Comment by backstreetkiwi** [comment]
@lfrancke I'd like to keep it, but lowest priority is okay for me.

**Comment by backstreetkiwi** [comment]
@lfrancke I made up my mind. Now that we rely almost completely on mK8s and the wireguard/VPN stuff is outdated/disabled anyway, this issue can be closed
