### ISSUE TITLE
AWS EKS on premise (spike)

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#171]
https://github.com/aws/eks-anywhere?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+thechangelog+%28The+Changelog%29

TODO: Research and find out if this is of any use for us.

**Comment by backstreetkiwi** [comment]
Hi @lfrancke, I remember you requested that. Is it still a thing?

**Comment by lfrancke** [comment]
No, let's close it until we have a need to reopen
