### ISSUE TITLE
Microsoft Azure integration

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#173]
- [x] Spike 
- [x] configuration: number of nodes, k8s version, ...
- [x] docs
- [x] reactivate AWS EKS if easy (timebox: approx 2hrs)
- [x] Please check if this is an option for us to save some money: https://opensource.microsoft.com/azure-credits#credits-apply (@stefanigel  took care of that)

**Comment by backstreetkiwi** [comment]
@lfrancke Do we have an Azure account already? I had a look at the link to the "open source credits" stuff. It says 

> Applications to the program will be reviewed and you will receive a notification of the decision within 3-4 weeks.


Maybe we don't want to wait that long?

**Comment by lfrancke** [comment]
We do. Please ask @razvan for access.

No, we don't want to wait that long but if you could take a look at the requirements and decide whether it makes sense to apply anyway that'd be great.

**Comment by backstreetkiwi** [comment]
Thanks, I'll ask him.
Regarding the credits: I looked into the questionnaire and it contains some business-related questions that are preferably answered by someone else.

**Comment by backstreetkiwi** [comment]
https://docs.microsoft.com/en-us/azure/developer/terraform/authenticate-to-azure?tabs=bash
