### ISSUE TITLE
Switch T2 over to applying CRDs from /etc/stackable/xxx-operator/crd 

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/t2#175]
T2 should use the packaged versions of the CRDs to ensure that we do not forget to package these. This just bit us with a customer.

Additionally we should also add integration test cases to ensure that all CRDs have been added to the commandline as well.

**Comment by backstreetkiwi** [comment]
@soenkeliebau The first part was done in #178

**Comment by backstreetkiwi** [comment]
This is outdated as we now work with Helm/Docker
