### ISSUE TITLE
enhance security of T2

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#2]
Some things that we have to do before the system really spins up machines in the cloud:

- [x] authentication via Token
- [x] max. number of clusters
- [x] feature toggle to switch off creation completely
- [x] https
- [x] peer review with focus on security issues

**Comment by backstreetkiwi** [comment]
During the security audit with @lfrancke, no major issues turned up. Some minor issues to deal with later:
- T2 should not run as root
- firewalld should be turned off for good (even after restart)
- t2 service should be enabled (not only started)
- security token file should be only readable by root

**Comment by lfrancke** [comment]
- An alternative to firewalld off is to configure it properly
- the token file should only be readable by the use running t2 (which doesn't have to be root)
