### ISSUE TITLE
Persistent cluster state/graceful restarts

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#247]
Due to the fact that the cluster state that T2 stores is in-memory, we lose this state with every new start (e.g. deployment) of T2. 
This is annoying as we cannot shutdown a cluster created by T2 after a deployment.
Depending on the cloud vendor, this comes with a lot of UI forms to work through in order to tear a cluster down w/o having the Terraform state.
We should have a mechanism to pick up the running clusters after a restart.
Additionally, to prevent T2 to leave clusters in an undefined state, we should have a "graceful restart" option. This includes switching T2 to a state of "shutdown in progress" before the actual restart. This prevents new clusters from being created while giving time for the clusters being provisioned or torn down to proceed this process. Ideally, there is an API endpoint to request the state.

**Comment by teozkr** [comment]
1. How complex is this setup procedure typically?
2. Would it make sense to retry steps that are in progress rather than trying hard to avoid inconsistency? Crashes /are/ going to happen eventually and so on...

**Comment by backstreetkiwi** [comment]
T2 is discontinued
