### ISSUE TITLE
scaling of clusters

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#29]
Originally, T2 has been designed to create complete clusters in one go.
In the future, we want T2 to be able to scale clusters up and down.
Therefore, we'll have to change the Ansible files to scale dependent on the Terraform state. (At least this is one idea to solve it).

**Comment by lfrancke** [comment]
@backstreetkiwi Is this still relevant?
(I assume so)

**Comment by backstreetkiwi** [comment]
@lfrancke 
tl;dr : Dunno. 

The tests we run do not need that AFAIK. If it is something nice to have for the "second T" (troubleshooting), I don't know. I would say it depends a little on which course we take in terms of managed K8ss...

**Comment by backstreetkiwi** [comment]
This has never been requested by any developer, so I close it. If somebody requests it in the future, we could open a new ticket, there's no knowledge whatsoever hidden in this issue.
