### ISSUE TITLE
distribute ssh keys into running cluster

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#34]
Sometimes it would be nice to add an ssh key to an already running cluster...

**Comment by lfrancke** [comment]
@backstreetkiwi Is this still relevant? (I assume so)

**Comment by backstreetkiwi** [comment]
@lfrancke Nobody asked me about that...

**Comment by backstreetkiwi** [comment]
As we're testing on (managed) K8s these days anyway, there's no need for this feature anymore.
(fyi @Jimvin)
