### ISSUE TITLE
Support MIME type application/yaml 

### ISSUE THREAD

**Issue by keeefin** [stackabletech/t2#35]
At the moment the server creates an unvalid zip file if the mime type is set to application/yaml and the file send is of type yaml (with curl). If send with json it works well. As you can see in swagger it tells us that the server supports only json. As of yaml is a superset, and your clusterdefinition function already supports this i think the issue is in the controller. 

in https://github.com/stackabletech/t2/tree/diy-support-multi-mime-type you can see that i changed the signature of the getmapping. Do you have more places in mind where this issue could be adressed? 

Regards 
Kev

**Comment by backstreetkiwi** [comment]
I picked your commit and added another mime mapping for another endpoint
