### ISSUE TITLE
Investigate and fix test flakiness

### ISSUE THREAD

**Issue by razvan** [stackabletech/t2#368]
## Description

The integration  tests fail intermittently with Jenkins/k3s

## Possible strategies

1. Reduce the amount of integration tests

* Do more unit testing https://github.com/stackabletech/issues/issues/269
* Run a reduced number of tests in the nightly CI: https://github.com/stackabletech/issues/issues/245

2. New integration testing tools

* KuttlNG https://github.com/stackabletech/issues/issues/265

3. Find one setup that is reliable

* Azure, GCP, AWS, ... ?
* What form of parallelism works?
* Image size ?
* Investigate the timeouts for test steps and asserts - @razvan , @siegfriedweber 
* Increase timeouts x 3 for every failed test
* Preload images in the cluster before actually starting the tests
* As the first results show that K3s might be a cause of the flakiness, we decided on 2022-09-19 to switch all nightly tests to mK8s variants which is done by @backstreetkiwi and requires this ticket: https://github.com/stackabletech/ci/issues/9
* Ticket to raise K3s cluster stability: https://github.com/stackabletech/t2/issues/371

4. Try to find the source of flakiness

* Aggregate + Analyze logs - https://github.com/stackabletech/infrastructure/issues/58 , @maltesander 
* Try to find if the same tests fail over and over again with high proba. - @vsupalov 
* Aggregate logs in OpenSearch or similar so that we can perform analysis with queries, etc. NEW task: https://github.com/stackabletech/t2/issues/370
* Use json report from kuttl - @backstreetkiwi (Is that still required? We have the job which extracts all the data we want from the logs already: https://github.com/stackabletech/infrastructure/issues/58)

* Try to reproduce the flakiness:
  * Generate the tests once and re-run them in a loop - @soenkeliebau , @razvan , @vsupalov https://github.com/stackabletech/druid-operator/issues/303
  * Reuse the cluster for multiple runs (one in k3s, Azure, etc.) - @soenkeliebau , @razvan , @vsupalov https://github.com/stackabletech/druid-operator/issues/303
  * Remove test containers from the tests to reduce the amount of test steps
  * Use the testing-tools image instead of pip install at test step time - @sbernauer , @maltesander 
  
5. Use the getting started guides as baseline

* Run GS-scripts and verify if they are more stable than the `kuttl` tests. - @adwk67 https://github.com/stackabletech/issues/issues/272

## Acceptance criteria

* Figure out why OR figure out a setup where the tests are running reliably

**Comment by lfrancke** [comment]
Can we close this?
Some things we have closed, others we will not do at the moment and the flakiness seems to be gone for now.

**Comment by lfrancke** [comment]
Thanks. I'll close it for now. We can always reopen.
