### ISSUE TITLE
Make orchestrator a countable ressource and refactor all count index

### ISSUE THREAD

**Issue by keeefin** [stackabletech/t2#37]
For better a cleander templating in the local file and tpl section make orchestrator a countable ressource. this also enables multi node controlplane.

Plus: Change the name in blocks from [= node_type ]-storage-${count.index + 1} to [= node_type ]-[= node_type ]-storage-${count.index + 1}-storage

this will lead to 
worker-1-storage
worker-2-storage

instead of 
worker-storage-1
worker-storage-2

you are iterating over the nodes not over the volumes, nics and so. If you have count on storages etc. we need to iterate them to.

change in code like
from
```
volume {
    name = "[= node_type ]-storage-${count.index + 1}"
    size = [= node_spec.diskSizeGb ]
    disk_type = "[= node_spec.diskType ]"
  }
```
to
```
volume {
    name = "[= node_type ]-${count.index + 1}-storage"
    size = [= node_spec.diskSizeGb ]
    disk_type = "[= node_spec.diskType ]"
  }
```

**Comment by backstreetkiwi** [comment]
As of now, we're focusing on integration tests which do not require multi node controlplanes. Therefore, we won't work further on this task now but instead put it back to the backlog. Nevertheless, we fix the misleading indexing as requested!

**Comment by backstreetkiwi** [comment]
indexing fixed in #41, ticket will be pushed to backlog (see comment above)

**Comment by lfrancke** [comment]
Is this still relevant?

**Comment by backstreetkiwi** [comment]
I don't think so
