### ISSUE TITLE
Cluster observability spike

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#370]
During our discussions for https://github.com/stackabletech/t2/issues/368, we found out that the current logs are not sufficient to do a proper troubleshooting of the tests.

As an operator developer who is investigating a test failure, I ...

* ... would like to be able to access the log data of a test even if the cluster is already destroyed
* ... would like to be able to easily search the log data
* ... would like to have the following data about my test run:
  * operator logs of all the Stackable operators running in the cluster
  * event log of the K8s control plane
  * pod change log of the K8s control plane?
  * (if possible) systemd journal of the Kubelets
  * more (I'm greedy)

comments:
* an article we stumbled upon while researching: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/
* (!) Differentiation: The logging ticket https://github.com/stackabletech/issues/issues/202 targets mostly the application/operator aspect of logging AND it will take some time before the results can be used here.

**Comment by vsupalov** [comment]
Not a long-term solution, but an interesting experiment to try: An observability product recently caught my eye - https://www.groundcover.com/. They promise A LOT. Out of the box. Could be useful to tune our expectations.

It's a bit pricy to use at scale (the pricing is at 20$ per node per month), but we can try it with up to 3 nodes for free.

**Comment by teozkr** [comment]
Audit logging and operator/product logging are two separate problems that we need to handle.

We already have a very simplistic auditing solution in place (running `kubectl get --watch` for the object types we care about), even if it's not 100% reliable or comprehensive.

I think the "easy" way to handle the product logging problem (for now) would be to deploy [Vector in Kubernetes mode](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/), which just slurps up all logs from all pods running in the cluster, and [dumps it into a file](https://vector.dev/docs/reference/configuration/sinks/file/) or wherever else.

**Comment by backstreetkiwi** [comment]
@teozkr I was aware of that. See the last comment in the description. Thank you for the idea of using Vector. This could actually be a low hanging fruit.
> Audit logging and operator/product logging are two separate problems that we need to handle.

**Comment by backstreetkiwi** [comment]
Spike is up and running and will be demonstrated in the Stackable review on 2022-11-09. 
Follow-up tasks have been created.
