### ISSUE TITLE
Support for AWS EKS version 1.23 and newer

### ISSUE THREAD

**Issue by razvan** [stackabletech/t2#372]
## Description
Kubernetes 1.23 kicked-off the [CSI migration](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#csi-migration-updates).

EKS versions 1.23 has removed the [EBS CSI provider](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) from the Kubernetes tree.This provider needs to be [added and configured separately](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html) in Kubernetes clusters from this version on.

## Acceptance criteria

- [x] T2 configures the EBS  provisioner for AWS EKS clusters  starting at version 1.23 upwards.
- [x] T2 enables dynamic provisioning of EBS volumes.
- [ ]  Optional: T2 can statically provision EBS volumes.
- [x] Installation of the `postgresql` Helm chart completes successfully on EKS version 1.23.

**Comment by backstreetkiwi** [comment]
Here's the Terraform resource to create configure an add-on in a cluster: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon

**Comment by backstreetkiwi** [comment]
Feature is implemented and tested in a dev environment.
TODOs:

- [ ] run the Airflow test on a 1.23 and 1.24 cluster
- [ ] release T2
- [ ] remove 1.22 from testsuites and defaults
- [ ] communicate changes
