### ISSUE TITLE
remove K3s default node?

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#58]
When we launch a cluster with T2, K3s starts a default node/kubelet on the same machine where K3s runs. It does not seem to be a problem in the current test setups, but there might be some interference if pods are scheduled on this node which is not part of the Stackable cluster. Should we remove that node via kubectl during the provisioning of the cluster?

**Comment by lfrancke** [comment]
For what it's worth.

This is how I start k3s on my local machine:

```
k3s server --data-dir ~/.rancher/k3s --disable-cloud-controller --disable-scheduler --disable-agent --disable-kube-proxy --disable-network-policy --disable coredns \
--disable servicelb --disable traefik --disable local-storage \
--disable metrics-server
```

**Comment by lfrancke** [comment]
I think we can leave the kubelet running. This paves an easy way for us to package our Operators as Docker images and deploy them within Kubernetes itself.

**Comment by lfrancke** [comment]
Thinking about this again I think it'd be great if this were configurable.

**Comment by lfrancke** [comment]
@backstreetkiwi This is not needed anymore, is it?

**Comment by backstreetkiwi** [comment]
@lfrancke Right.
