### ISSUE TITLE
Add endpoint to download kubeconfig

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/t2#60]

**Comment by backstreetkiwi** [comment]
If you work with a Stackable cluster using a VPN, you might want to use the Kubernetes-Tools (k9s, kubectl, ...) from your machine. For that to work, we should offer a way to download an appropriate kubeconfig

- [ ] copy kubeconfig as resource during provisioning
- [ ] provide endpoint
- [ ] docs
