### ISSUE TITLE
Speed up Ansible provisioning

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/t2#61]
The provisioning of a Stackable cluster using T2 takes quite a while. During the preparation for a Hackathon we came up with several ideas that should be checked:

- [x] pipelining Ansible (reusing SSH connections) 

(In the meantime we use it but it seems not to make a difference. Do we use it correctly?)

- [ ] using cloud-init/cloud-config (supported by IONOS!)

The following links might contain ideas/hints/tools to use:

- https://www.digitalocean.com/community/tutorials/how-to-configure-custom-connection-options-for-your-ssh-client
- https://shadow-soft.com/turbo-charge-your-ansible/
- https://mitogen.networkgenomics.com/ansible_detailed.html

- [x] make wireguard stuff optional to save time

**Comment by lfrancke** [comment]
I've put it in the backlog again but mostly for you to comment on how useful you think this'll be.

I can't really judge this. Do you have a gut feeling how useful this would be now?

**Comment by backstreetkiwi** [comment]
As we're more and more switching to managed K8s clusters, I think you won't prioritize this ticket anyway. Furthermore, I don't know how much potential of speeding up the provisioning lies in the cloudinit stuff, as the setup of a k3s cluster requires cooperation between the nodes anyway and cannot be baked into prepared images.

**Comment by lfrancke** [comment]
Okay. So we'll close it. Thank you
