### ISSUE TITLE
Configure daemon.log and syslog with logrotate on a size basis

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/t2#94]
Currently both of these files can consume an unlimited amount of space which can happen when an operator has an error.

It'd be good if these log files were rotated on a "size" basis so they can never consume more than (say) 50% of all space.
I'm not sure why/when these files exist at all because I thought it's all in the journalctl database.

**Comment by lfrancke** [comment]
The scope of this issue has changed slightly or will change after the move to K8s as logs will be written by the operators inside containers.

Please use this issue to investigate briefly if there is anything we can/should do to limit file system usage by containers to avoid running out of space.

If the answer turns out to be: No feel free to close this issue.
If the answer is "Yes, but it's complicated and will take days to fix" please talk to me before talking it further.

**Comment by backstreetkiwi** [comment]
I guess we can close this.
